version: 0.0
os: linux
file:
  - source: /
    destination: /var/www/html
Hook: 
  AfterInstall:
    - location: script/install_nginx.sh
      timeout: 300
      runas: root
  applicationstart:
    - location: script/start_nginx.sh
      timeout: 300
      runas: root